---
title: "R Notebook"
output: html_notebook
---


```{r}
#install.packages("gridExtra")
library(lubridate)
library(dplyr)
library(ggplot2)
library(kableExtra)
library(tidyr)
library(gridExtra)
df <- read.csv("C:\\Users\\UNS_CT\\Desktop\\oenggii\\project\\New folder\\total_cases.csv")
df$date <- as.Date(df$date)
df
df %>% ggplot(aes(x=date, y=World))+geom_line(colour="red")+labs(title=paste0('Numbers of Cases Worldwide (log scale) '))+scale_y_continuous(trans='log10')

```
```{r}
df_full <- read.csv("C:\\Users\\UNS_CT\\Desktop\\oenggii\\project\\full_data.csv")
df_full
df_full$date <- as.Date(df_full$date,tryFormats = c("%m/%d/%Y", "%Y-%m-%d"))
df_full
df_full <- rename(df_full,c(country=location))
df_full %>% filter(country=='China') %>% head(10)%>% kable(caption = 'Raw data(with first 10 Columns Only)',format.args=list(big.mark=','))%>%kable_styling(latex_options = c('striped', 'hold_position', 'repeat_header'))
# df_long <- gather(df_full,key=date,value = count,new_cases:biweekly_deaths)
# df_long <- mutate(df_long,date = date)
# df_long <- group_by(country,date) %>% summarise(count=sum(count,na.rm=T))%>%as.data.frame()
df_full <- select(df_full, -c (weekly_cases,weekly_deaths,biweekly_cases,biweekly_deaths))
df_full
df_world <- df_full %>% group_by(date) %>% summarise(country='World',
                                         new_cases= sum(new_cases, na.rm=T),
                                         new_deaths=sum(new_deaths,na.rm = T),
                                         total_cases=sum(total_cases,na.rm = T),
                                         total_deaths=sum(total_deaths,na.rm=T))
df_world
df_total <-rbind(df_world) 
df_total

world_plot1 <- ggplot(df_total, aes(x=date, y=total_cases)) + geom_point()+geom_smooth() + xlab('Date') + ylab('Count') +      labs(title = 'Total Case') + theme(axis.text.x=element_text(angle=45, hjust=1))

world_plot2 <- ggplot(df_total, aes(x=date, y=new_cases)) + geom_point() + geom_smooth() + xlab('Date') + ylab('Count') +
  labs(title = 'New Case') + theme(axis.text.x = element_text(angle=45,hjust=1))

grid.arrange(world_plot1, world_plot2, ncol=2)
```
```{r}
data.long <- df_total %>% gather(key=type, value=count, -c(country,date))
data.long
world_plot3 <- data.long %>% ggplot(aes(x=date, y=count)) + geom_area(aes(fill=type), alpha=0.5) + 
            labs(title = paste0('Numbers of Cases Worldwide -')) + scale_fill_manual(values=c('red','green','black','blue'))+   theme(legend.title = element_blank(), legend.position = 'bottom',plot.title = element_text(size=7),
                 axis.title.x = element_blank(),axis.title.y = element_blank(),legend.key.size = unit(0.2,'cm'),
                 legend.text=element_text(size = 6),axis.text = element_text(size=7),
                axis.text.x = element_text(angle = 45,hjust=1))
world_plot3
```



