---
title: "Covid19 Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(readxl)
library(tidyverse)
library(plotly)
library(ggmap)
library(DT)
library(gridExtra)
library(dplyr)
library(lubridate)
library(magrittr)
library(ggplot2)
library(tidyr)
library(knitr)
library(normalr)
library(ggcorrplot)
library(leaflet)
library(RColorBrewer)
library(readr)

#??src_mysql
my_db <- src_mysql(
  dbname = "covid",
  host = "127.0.0.1",
  user = "root",
  password = "1234"
)
my_db

##import data
df_conf <- tbl(my_db, sql("select * from covid19_confirmed"))
df_conf <- as.data.frame(df_conf) 
df_deaths <- tbl(my_db, sql("select * from covid19_deaths"))
df_deaths <- as.data.frame(df_deaths)
df_recover <- tbl(my_db, sql("select * from covid19_recovered"))
df_recover <- as.data.frame(df_recover)
n.col <- ncol(df_conf)
dates <- names(df_conf)[5:n.col]%>% mdy()
range(dates)
min.date <- min(dates)
max.date <- max(dates)
min.date.txt <- min.date %>% format('%d %b %Y')
max.date.txt <- max.date %>% format('%d %b %Y')

cleanData <- function(data) {
  ## remove some columns
  data %<>% select(-c(Province.State, Lat, Long)) %>% dplyr::rename(country=Country.Region)
  ## convert from wide to long format
  data %<>% gather(key=date, value=count, -country)
  ## convert from character to date
  data %<>% mutate(date = date %>% mdy())
  ## aggregate by country
  data %<>% group_by(country, date) %>% dplyr::summarise(count=sum(count, na.rm=T)) %>% as.data.frame()
  return(data)
}
#View(df_conf)

## clean the three data sets
data.confirmed <- df_conf %>% cleanData() %>% dplyr::rename(confirmed=count)
data.deaths <- df_deaths %>% cleanData() %>% dplyr::rename(deaths=count)
data.recovered <- df_recover %>% cleanData() %>% dplyr::rename(recovered=count)
data <- data.confirmed %>% merge(data.deaths, all=T) %>% merge(data.recovered, all=T)
#View(data)

## countries/regions with confirmed cases, excl. cruise ships
countries <- data %>% pull(country) %>% setdiff('Cruise Ship')
View(data)

#-------- import data --------
#source("Coronavirus.Rmd",local = TRUE)

```
Over All
===
Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

```

US
===
Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

Thailand
===
### Chart B

```{r}

```

### Chart C

```{r}

```
Data Summary
===
```{r}


```

