---
title: "ODBC with SQL"
output: html_notebook
---
```{r}
#install.packages("DBI")
#install.packages("odbc")
#install.packages("lubridate")
#install.packages("RODBC")
#install.packages("ggplot2")
#install.packages("tidyr")
#install.packages("plyr")
#install.packages("magrittr")
install.packages("kableExtra")
```

```{r}
#library(DBI)
library(odbc)
library(lubridate)
#library(RODBC)
library(ggplot2)
#library(tidyr)
library(plyr)
library(magrittr)
library(kableExtra)
```

```{r}
con <- dbConnect(odbc::odbc(), "MYSQL_ODBC")
odbcConnectionIcon(con)
```
```{r}
#Full data
q.confirmed <- dbSendQuery(con, "SELECT * FROM time_series_covid19_confirmed_global")
confirmed_cases <- dbFetch(q.confirmed) %>% 
  rename(c("Country.Region" = "Country"))
View(confirmed_cases)
```

```{r}
dates <- names(confirmed_cases)[5:ncol(confirmed_cases)] %>% mdy()
range(dates)
```

```{r}
q.deaths <- dbSendQuery(con, "SELECT * FROM time_series_covid19_deaths_global")
deaths_cases <- dbFetch(q.deaths) %>% 
  rename(c("Country.Region" = "Country"))
View(deaths_cases)
```

```{r}
q.recovered <- dbSendQuery(con, "SELECT * FROM time_series_covid19_recovered_global")
recovered_cases <- dbFetch(q.recovered) %>% 
  rename(c("Country.Region" = "Country"))
View(recovered_cases)
```

```{r}
#Top 10 all time
top10.all <- dbSendQuery(q.confirmed, "SELECT Country
                                FROM confirmed_cases
                                GROUP BY Country
                                #ORDER BY 8/31/2020 DESC
                                ")
top10.all_cases <- dbFetch(top10.all, n = 10)
top10.all_cases
```

```{r}
top10.all_casestop10.DeathPerCase <- dbSendQuery(con, "")
```

```{r}
#Weekly Top 10
top10.week <- dbSendQuery(con, "SELECT location, AVG(weekly_cases)
                                FROM full_datas
                                WHERE NOT location = 'World'
                                GROUP BY location
                                ORDER BY AVG(weekly_cases) DESC
                                ")
top10.weekly_cases <- dbFetch(top10.week, n = 10)
top10.weekly_cases

ggplot(top10.weekly_cases, aes(x = location, y = weekly_cases, group = 1)) + geom_line()
```

```{r}
dbListTables(con)

# List tables beginning with f
dbListTables(con, table_name = "%f")

# List all fields in the 'flights' database
```

```{r}
# Writing data
data <- dbWriteTable(con, "iris", iris)
```


```{r}
# Reading Tables
library(DBI)
library(RODBCDBI)
rodbc <- dbConnect(RODBCDBI::ODBC(), dsn = "PostgreSQL")
system.time(rodbc_result <- dbReadTable(rodbc, "flights"))
```

