---
title: "R Notebook"
output: html_notebook
---
```{r}
#install.packages("magrittr") #pipe operation
#install.packages("lubridate") #date operations
#install.packages("tidyverse") #ggplot2,tidyr,dplyr
#install.packages("gridExtra") #multiple grid-based plots on a page
#install.packages("ggforce") #accelerating ggplot2
#install.packages("kableExtra") #complex tables
#install.packages("leaflet") #map

library(magrittr)
library(lubridate)
library(tidyverse)
library(dplyr)
library(gridExtra)
library(ggforce)
library(kableExtra)
library(leaflet)
```

```{r}
raw.data.full_data <- read.csv("~/R-project/full_datas.csv")
View(raw.data.full_data)
dim(raw.data.full_data) # row 31978 column 10
```
```{r}
raw.data.full_data[1:10,1:10] %>%
  kable('latex',booktabs=T,caption='Raw Data (first 10 columns only)') %>%
  kable_styling(font_size=5,latex_options = c('striped','hold_position','repeat_header'))
View(raw.data.full_data)
```

```{r}
rdate <- as.Date(raw.data.full_data$date,"%Y-%m-%d")
range(rdate)

```
```{r}
raw.data.full_data %>% mutate(month=month(date)) %>%
  group_by(date) %>%
  summarize(avg_totalcase = mean(total_cases))%>%
  arrange(avg_totalcase)%>%
  top_n(3)
```
```{r}
data <- raw.data.full_data %>% filter(date == max(date))%>%
  select(location,date,new_cases,new_deaths,total_cases,total_deaths) %>%
  mutate(ranking = dense_rank(desc(total_deaths)))
n <- 10
top_country <- data %>% filter(ranking <= n+1) %>%
  arrange(ranking) %>% pull(location) %>% as.character()
top_country %>% setdiff('World') %>% print()
```
```{r}
data.latest <- data %>% filter(!is.na(location)) %>%
  mutate(location=ifelse(ranking <= n+1,as.character(location),'Other')) %>%
  mutate(location = location %>% factor(levels=c(top_country),'Other'))
data.latest %<>% group_by(location) %>%
  summarise(total_cases = sum(total_cases),new_cases = sum(new_cases), 
            total_deaths = sum(total_deaths),new_deaths = sum(new_deaths))%>%
  mutate(death.rate = (100*total_deaths/total_cases) %>% round(1))
data.latest %<>% select(c(location,total_cases,new_cases,total_deaths,new_deaths ))




```
```{r}

x <- raw.data.full_data
x$total_cases <- x[,ncol(x)]
x %<>% select(c(location,total_cases)) %>%
  mutate(txt=paste0(location, '-',total_cases))
m <- leaflet(width = 1200,height = 800) %>% addTiles()
m %<>% addCircleMarkers(x$)

```




```{r}
data.world <- raw.data.full_data %>% filter(location=='World') 
n <- nrow(data.world)
 ## current confirmed and daily new confirmed
plot1 <- ggplot(data.world, aes(x=date, y=total_cases)) + geom_point() + geom_smooth() +
xlab('') + ylab('Count') + labs(title='total Cases') + theme(axis.text.x=element_text(angle=45, hjust=1))
plot2 <- ggplot(data.world, aes(x=date, y=new_cases)) +
  geom_point() + geom_smooth() +
xlab('') + ylab('Count') + labs(title='Daily New  Cases') + theme(axis.text.x=element_text(angle=45, hjust=1))
## show two plots side by side
grid.arrange(plot1, plot2, ncol=2)
```




