---
title: "R Notebook"
output: html_notebook
---

 

```{r}
#Load add-on packages - deSolve - contains lsoda function - differential equation solver.
#install.packages("Metrics")
library(dplyr)
library(deSolve) 
library(ggplot2)
library(tidyverse)
library(ggcorrplot)
library(gridExtra)
library(dplyr)
library(Metrics)
library(lubridate)
```



```{r}
#Function to compute derivatives of the differential equations.
seir_modelThai = function (current_timepoint, state_values, parameters)
{
  # create state variables (local variables)
  S = state_values [1]        # susceptibles
  E = state_values [2]        # exposed
  I = state_values [3]        # infectious
  R = state_values [4]        # recovered
  
  with ( 
    as.list (parameters),     # variable names within parameters can be used 
         {
           # compute derivatives
           dS = (-beta * S * I)
           dE = (beta * S * I) - (delta * E)
           dI = (delta * E) - (gamma * I)
           dR = (gamma * I)
           
           # combine results
           results = c (dS, dE, dI, dR)
           list (results)
         }
    )
}
```

```{r}
#Parameters
contact_rate = 10834/366             # number of contacts per day
transmission_probability =  (100*10834)/69630000     # transmission probability
infectious_period = 5.2               # infectious period
latent_period = 14                    # latent period
#Compute Ro - Reproductive number.
#Ro = beta_value / gamma_value
#Ro = 2.006
```

```{r}
#Compute values of beta (tranmission rate) and gamma (recovery rate).
lambda = 0.8
#beta_value =  contact_rate * transmission_probability
beta_value = lambda * contact_rate * transmission_probability
#beta_value = lambda * Ro * (1 / infectious_period)
#beta_value = Ro * (1 / infectious_period)
gamma_value = 1 / infectious_period
delta_value = 1 / latent_period
Ro = beta_value / gamma_value
#Disease dynamics parameters.
parameter_list = c (beta = beta_value, gamma = gamma_value, delta = delta_value)
Ro
delta_value
```


```{r}
#Initial values for sub-populations.
W = 69630000        # susceptible hosts
X = 1           # infectious hosts
Y = 0           # recovered hosts
Z = 0           # exposed hosts
#Compute total population.
N = W + X + Y + Z
#Initial state values for the differential equations.
initial_values = c (S = W/N, E = X/N, I = Y/N, R = Z/N)
```

```{r}
#Output timepoints.
timepoints = seq (0, 500, by=1)
```

```{r}
#Simulate the SEIR epidemic.Without Protective
output1 = lsoda (initial_values, timepoints, seir_modelThai, parameter_list)
df1 <- as.data.frame(output1)
df1
```


```{r}
#Simulate the SEIR epidemic.With Protective
output2 = lsoda (initial_values, timepoints, seir_modelThai, parameter_list)
df2 <- as.data.frame(output2)
df2
```
```{r}
df2 <- as.data.frame(output2) %>% rename(SP="S",EP="E","IP"=I,"RP"=R)
df1 <- as.data.frame(output1)
```

```{r}
dfAll  <- merge(x = df1, y = df2, by = "time", all.x = TRUE) 
dfAll
```


```{r}
dfAll <- as.data.frame(dfAll)
dfAll
## a scatter plot with a smoothed line and vertical x-axis labels
plot1 <- 
ggplot(dfAll, aes(x=time,y=S)) + 
  geom_line(color = 'red') + geom_line(mapping = aes(y= SP),color = 'blue')+
  xlab('') + ylab('Fraction') + labs(title='Susceptible blue(With Protective)') +
  theme(axis.text.x=element_text(angle=45, hjust=1),
        plot.title = element_text(size=11))
plot2 <- ggplot(dfAll, aes(x=time, y=E)) +
  geom_line(color = 'red') + geom_line(mapping = aes(y= EP),color = 'blue')+
  xlab('') + ylab('Fraction') + labs(title='Exposed blue(With Protective)') +
  theme(axis.text.x=element_text(angle=45, hjust=1),
        plot.title = element_text(size=11))
plot3 <- ggplot(dfAll, aes(x=time, y=I)) +
  geom_line(color = 'red') + geom_line(mapping = aes(y= IP),color = 'blue')+
  xlab('') + ylab('Fraction') + labs(title='Infectious blue(With Protective)') +
  theme(axis.text.x=element_text(angle=45, hjust=1),
        plot.title = element_text(size=11))
plot4 <- ggplot(dfAll, aes(x=time, y=R)) +
  geom_line(color = 'red') + geom_line(mapping = aes(y= RP),color = 'blue')+
  xlab('') + ylab('Fraction') + labs(title='Recovered blue(With Protective)') +
  theme(axis.text.x=element_text(angle=45, hjust=1),
        plot.title = element_text(size=11))


## show four plots together, with 2 plots in each row
grid.arrange(plot1, plot2, plot3, plot4, nrow=2)
```


```{r}

colors <- c("S (Sensitive)" = "blue", "E (Exposed)" = "black", "I (Infected)" = "red", "R (Recovered)" = "green")


ggplot(df1, aes(x = time)) +
    geom_line(aes(y = S, color = "S (Sensitive)"), size = 1.5) +
    geom_line(aes(y = E, color = "E (Exposed)"), size = 1.5) +
    geom_line(aes(y = I, color = "I (Infected)"), size = 1.5) +
    geom_line(aes(y = R, color = "R (Recovered)"), size = 1.5) +
    labs(title = "SEIR model for Covid-19 in Thailand (Without Protective)",
         x = "Days from 12 January 2020",
         y = "Fraction of population",
         color = "Legend") +
    scale_color_manual(values = colors,breaks = c("S (Sensitive)", "E (Exposed)", "I (Infected)", "R (Recovered)")) 

```
```{r}
colors <- c("S (Sensitive)" = "blue", "E (Exposed)" = "black", "I (Infected)" = "red", "R (Recovered)" = "green")

ggplot(df2, aes(x = time)) +
    geom_line(aes(y = SP, color = "S (Sensitive)"), size = 1.5) +
    geom_line(aes(y = EP, color = "E (Exposed)"), size = 1.5) +
    geom_line(aes(y = IP, color = "I (Infected)"), size = 1.5) +
    geom_line(aes(y = RP, color = "R (Recovered)"), size = 1.5) +
    labs(title = " SEIR model for Covid-19 in Thailand (With Protective)",
         x = "Days from 12 January 2020",
         y = "Fraction of population",
         color = "Legend") +
    scale_color_manual(values = colors,breaks = c("S (Sensitive)", "E (Exposed)", "I (Infected)", "R (Recovered)"))
```

```{r}
my_db <- src_mysql(
  dbname = "covid19",
  host = "cvd-database.cmxpnyylhkiw.us-east-2.rds.amazonaws.com",
  user = "admin" ,
  password = "RprojectCovid19"
)
my_db

#Covid_Thailand
df_thai <- tbl(my_db, sql("select * from covid19_thailand"))
df_thai <- as.data.frame(df_thai)

```

```{r}
#clean Covid_Thailand
dates.th <- df_thai[,2]%>% mdy()
range(dates.th)
min.date.th <- min(dates.th)
max.date.th <- max(dates.th)
min.date.txt.th <- min.date.th %>% format('%d %b %Y')
max.date.txt.th <- max.date.th %>% format('%d %b %Y')
```

```{r}
df_thai$announce_date <- mdy(df_thai$announce_date)
df_thai$notification_date <- mdy(df_thai$notification_date)
df_thai
```


```{r}
df_thai <- df_thai %>% select(!No.) %>% select(!notification_date) %>% 
  group_by(announce_date)
df_thai
```

```{r}
# Total confirmed cases in Thailand
data.thai.count <- df_thai %>%
  select(announce_date) %>%
  summarise(comfirmed = n())  %>% as.data.frame()
data.thai.count$cumulative_confirmed <- cumsum(data.thai.count[, 2])
data.thai.count
```

```{r}
nrow(data.thai.count)
dataActualThai <- data.thai.count  %>% mutate(time = row_number() ) 
dataActualThai <- dataActualThai[1:7,]
dataActualThai
```

```{r}
dfmodelThai <- df2 %>% mutate(IP = IP * 69630000  %>% round(1)) 
dfmodelThai 
```

```{r}
dfAllmodelThai  <- merge(x = dataActualThai, y = dfmodelThai, by = "time", all.x = TRUE) 
dfAllmodelThai
```

```{r}
library(Metrics) 
  
# Taking two vectors 
actual =   dfAllmodelThai$cumulative_confirmed         
predicted =  dfAllmodelThai$IP       
  
# Calculating RMSE using rmse()          
resultThai = rmse(actual, predicted) 
  
# Printing the value 
print(resultThai) 
```

```{r}
plotRmseThai <- 
ggplot(dfAllmodelThai, aes(x=time,y=IP)) + 
  geom_line(color = 'red') + geom_line(mapping = aes(y= cumulative_confirmed),color = 'blue')+
  xlab('') + ylab('case') + labs(title='SEIR model and Confirmed case') +
  theme(axis.text.x=element_text(angle=45, hjust=1),
        plot.title = element_text(size=11))
plotRmseThai
```




```{r}
#Function to compute derivatives of the differential equations.
seir_modelUS = function (current_timepoint, state_values, parameters)
{
  # create state variables (local variables)
  S = state_values [1]        # susceptibles
  E = state_values [2]        # exposed
  I = state_values [3]        # infectious
  R = state_values [4]        # recovered
  D = state_values [5]        # deaths
  
  with ( 
    as.list (parameters),     # variable names within parameters can be used 
         {
           # compute derivatives
           dS = (-beta * S * I)
           dE = (beta * S * I) - (delta * E)
           dI = (delta * E) - (gamma * I)
           dR = (gamma * I) * (1-sigma)
           dD = (gamma * I * sigma)
           
           # combine results
           results = c (dS, dE, dI, dR, dD)
           list (results)
         }
    )
}

```

```{r}

#Parameters
#contact_rate = 10                # number of contacts per day
#transmission_probability = 0.07 #24441852/328200000  # transmission probability
infectious_period = 14         # infectious period 10-20
latent_period = 5.2              # latent period
deaths_period = 406196/24441852


Ro = 2.5 #1.9-3.3 

#Compute values of beta (tranmission rate) and gamma (recovery rate).
#beta_value = contact_rate * transmission_probability
lambda = 0.8
#beta_value = lambda * contact_rate * transmission_probability
beta_value = lambda * Ro * (1 / infectious_period)
#beta_value = Ro * (1 / infectious_period)
gamma_value = 1 / infectious_period
delta_value = 1 / latent_period
sigma_value = deaths_period

#Compute Ro - Reproductive number.
#Ro = beta_value / gamma_value
Ro

#Disease dynamics parameters.
parameter_list = c (beta = beta_value, gamma = gamma_value, delta = delta_value,sigma = sigma_value)

#Initial values for sub-populations.
W = 328200000   # susceptible hosts
X = 1           # infectious hosts
Y = 0           # recovered hosts
Z = 0           # exposed hosts
A = 0

#Compute total population.
N = W + X + Y + Z + A

#Initial state values for the differential equations.
initial_values = c (S = W/N, E = X/N, I = Y/N, R = Z/N, D = A/N)

#Output timepoints.
timepoints = seq (0, 500, by=1)


```

```{r}
#Simulate the SEIR epidemic.
output3 = lsoda(initial_values, timepoints, seir_modelUS, parameter_list)
df3 <- as.data.frame(output3)
df3
```

```{r}
#Simulate the SEIR epidemic.
output4 = lsoda(initial_values, timepoints, seir_modelUS, parameter_list)
df4 <- as.data.frame(output4)
df4
```
```{r}
df4 <- as.data.frame(output4) %>% rename(SP="S",EP="E","IP"=I,"RP"=R,"DP"=D)
df3 <- as.data.frame(output3)
```

```{r}
dfAll2  <- merge(x = df3, y = df4, by = "time", all.x = TRUE) 
dfAll2
```

```{r}
dfAll2 <- as.data.frame(dfAll2)
dfAll2
## a scatter plot with a smoothed line and vertical x-axis labels
plot1 <- 
ggplot(dfAll2, aes(x=time,y=S)) + 
  geom_line(color = 'red') + geom_line(mapping = aes(y= SP),color = 'blue')+
  xlab('') + ylab('Fraction') + labs(title='Susceptible blue(With Protective)') +
  theme(axis.text.x=element_text(angle=45, hjust=1),
        plot.title = element_text(size=11))
plot2 <- ggplot(dfAll2, aes(x=time, y=E)) +
  geom_line(color = 'red') + geom_line(mapping = aes(y= EP),color = 'blue')+
  xlab('') + ylab('Fraction') + labs(title='Exposed blue(With Protective)') +
  theme(axis.text.x=element_text(angle=45, hjust=1),
        plot.title = element_text(size=11))
plot3 <- ggplot(dfAll2, aes(x=time, y=I)) +
  geom_line(color = 'red') + geom_line(mapping = aes(y= IP),color = 'blue')+
  xlab('') + ylab('Fraction') + labs(title='Infectious blue(With Protective)') +
  theme(axis.text.x=element_text(angle=45, hjust=1),
        plot.title = element_text(size=11))
plot4 <- ggplot(dfAll2, aes(x=time, y=R)) +
  geom_line(color = 'red') + geom_line(mapping = aes(y= RP),color = 'blue')+
  xlab('') + ylab('Fraction') + labs(title='Recovered blue(With Protective)') +
  theme(axis.text.x=element_text(angle=45, hjust=1),
        plot.title = element_text(size=11))
plot5 <- ggplot(dfAll2, aes(x=time, y=D)) +
  geom_line(color = 'red') + geom_line(mapping = aes(y= DP),color = 'blue')+
  xlab('') + ylab('Fraction') + labs(title='Deaths blue(With Protective)') +
  theme(axis.text.x=element_text(angle=45, hjust=1),
        plot.title = element_text(size=11))


## show four plots together, with 2 plots in each row
grid.arrange(plot1, plot2, plot3, plot4,plot5,nrow=3)
```


```{r}

colors <- c("S (Sensitive)" = "blue", "E (Exposed)" = "black", "I (Infected)" = "red", "R (Recovered)" = "green","D (Deaths)" = "purple")

ggplot(df3, aes(x = time)) +
    geom_line(aes(y = S, color = "S (Sensitive)"), size = 1.5) +
    geom_line(aes(y = E, color = "E (Exposed)"), size = 1.5) +
    geom_line(aes(y = I, color = "I (Infected)"), size = 1.5) +
    geom_line(aes(y = R, color = "R (Recovered)"), size = 1.5) +
    geom_line(aes(y = D, color = "D (Deaths)"), size = 1.5) +
    labs(title = " SEIRD model for Covid-19 in US (Without Protective)",
         x = "Days from 21 January 2020",
         y = "Fraction of population",
         color = "Legend") +
    scale_color_manual(values = colors,breaks = c("S (Sensitive)", "E (Exposed)", "I (Infected)", "R (Recovered)","D (Deaths)"))


```

```{r}
colors <- c("S (Sensitive)" = "blue", "E (Exposed)" = "black", "I (Infected)" = "red", "R (Recovered)" = "green","D (Deaths)" = "purple")

ggplot(df4, aes(x = time)) +
    geom_line(aes(y = SP, color = "S (Sensitive)"), size = 1.5) +
    geom_line(aes(y = EP, color = "E (Exposed)"), size = 1.5) +
    geom_line(aes(y = IP, color = "I (Infected)"), size = 1.5) +
    geom_line(aes(y = RP, color = "R (Recovered)"), size = 1.5) +
    geom_line(aes(y = DP, color = "D (Deaths)"), size = 1.5) +
    labs(title = " SEIRD model for Covid-19 in US (With Protective)",
         x = "Days from 21 January 2020",
         y = "Fraction of population",
         color = "Legend") +
    scale_color_manual(values = colors,breaks = c("S (Sensitive)", "E (Exposed)", "I (Infected)", "R (Recovered)","D (Deaths)"))
```

```{r}
#Covid_US
df_us <- tbl(my_db, sql("select * from covidus"))
df_us <- as.data.frame(df_us)
df_us
```

```{r}
#clean Covid_US
dates.us <- df_us[,2]%>% mdy()
range(dates.us)
min.date.us <- min(dates.us)
max.date.us <- max(dates.us)
min.date.txt.us <- min.date.us %>% format('%d %b %Y')
max.date.txt.us <- max.date.us %>% format('%d %b %Y')
```

```{r}
df_us <- df_us %>% select(!MyUnknownColumn) %>% select(!fips) %>% 
  group_by(date)
df_us
```
```{r}
data.us.total <- df_us %>% group_by(date) %>%
  summarise(state ='US',
            cases = sum(deaths,na.rm=T),
            deaths = sum(deaths,na.rm=T))

```
```{r}
nrow(data.us.total)
dataActualUs <- data.us.total  %>% mutate(time = row_number() ) 
dataActualUs <- dataActualUs[1:7,]
dataActualUs
```

```{r}
dfmodelUs <- df4 %>% mutate(IP = IP * 328200000  %>% round(1)) 
dfmodelUs 
```

```{r}
dfAllmodelUs  <- merge(x = dataActualUs, y = dfmodelUs, by = "time", all.x = TRUE) 
dfAllmodelUs
```

```{r}
library(Metrics) 
  
# Taking two vectors 
actual =   dfAllmodelUs$case         
predicted =  dfAllmodelUs$IP       
  
# Calculating RMSE using rmse()          
resultUs = rmse(actual, predicted) 
  
# Printing the value 
print(resultUs) 
```

```{r}
plotRmseUs <- 
ggplot(dfAllmodelUs, aes(x=time,y=IP)) + 
  geom_line(color = 'red') + geom_line(mapping = aes(y= cases),color = 'blue')+
  xlab('') + ylab('cases') + labs(title='SEIRD model and Confirmed cases') +
  theme(axis.text.x=element_text(angle=45, hjust=1),
        plot.title = element_text(size=11))
plotRmseUs
```



















































