---
title: "Weather"
output: html_notebook
---
```{r}
#install.packages("RODBC")
#install.packages("odbc")
#install.packages("reshape2")
#install.packages("ggplot2")
#install.packages("plyr")
#install.packages("sqldf")
#install.packages("data.table")
#install.packages("gridExtra")
#install.packages("raster")
#install.packages("leaflet")
```

```{r}
library(RODBC) #connect mysql
#library(odbc) #connect mysql
library(lubridate) #date operation
library(magrittr ) #pipe operation
library(reshape2)
library(ggplot2)
library(plyr)
library(sqldf)
library(gridExtra)
library(gridExtra)
#library(raster)
library(leaflet)
```

```{r}
data <- odbcConnect("coronavirus19",uid = "root",pwd = "1234" )

raw.confirmed <- sqlQuery(data, "SELECT * FROM covid19_confirmed_global")
raw.deaths <- sqlQuery(data, "SELECT * FROM covid19_deaths_global")
raw.recovered <- sqlQuery(data, "SELECT * FROM covid19_recovered_global")

n.col <- ncol(raw.confirmed)
## get dates from column names
dates <- names(raw.confirmed)[5:n.col] %>% mdy()
range(dates)

min.date <- min(dates)
max.date <- max(dates)
min.date.txt <- min.date %>% format('%d %b %Y')
max.date.txt <- max.date %>% format('%d %b %Y') %>% paste('UTC')


cleanData <- function(data){
  data <- data[,!(names(data) %in% c("Province.State","Lat","Long"))]%>%rename(c("Country.Region"="country"))
  data <- melt(data,id = c("country")) %>% rename(c("variable" = "date"))%>% rename(c("value"="count"))
  data <- aggregate(. ~ country + date , data = data, sum, na.rm=TRUE)%>% as.data.frame()
  data$date <- as.Date(data$date,tryFormats = c("%m/%d/%Y", "%Y-%m-%d")) 
 return(data)
}
dataConfirmed <- raw.confirmed %>% cleanData()%>% rename(c("count"="confirmed"))
dataDeaths <- raw.deaths %>% cleanData() %>% rename(c("count"="deaths"))
dataRecovered <- raw.recovered %>% cleanData() %>% rename(c("count"="recovered"))
#dataConfirmed

data_total <- dataConfirmed %>% merge(dataDeaths,all = T) %>% merge(dataRecovered,all = T)


#check str
#str(data_total)
#View(data_total)
View(data_total)
```

```{r}
#counts for the whole world

##dataDate <- sqldf("SELECT * FROM data_total group by Date")
#data_total1 <- subset(data_total1, select = -c(Country))
#world.Total <- aggregate(x = data_total[c("confirmed", "deaths", "recovered")], by = list(country = data_total$Country, date = data_total$Date), sum)
#world.Total

data(data_total)
head(data_total)

#change country to "World"
data_total1 <- data_total
data_total1$country <- "World"

#group data by date and sum all (confirmed, deaths, recovered) cases
dataWorld  <- aggregate(. ~ country + date , data = data_total1, sum, na.rm=TRUE)
#dataWorld 
#View(dataWorld)

#merge 'World' statistic to main data frame
data_total <- rbind(data_total, dataWorld)
data_total <- sqldf("SELECT * FROM data_total group by country, date order by country", drv='SQLite')
#current confirmed cases
data_total$current.confirmed <- data_total$confirmed - data_total$deaths - data_total$recovered
data_total 
View(data_total)

```
```{r}
world.long <- data.long[data.long$country == 'World',]
rownames(world.long) <- NULL
#world.long
#case-area plot
plot1 <- world.long[world.long$Type != 'Total Confirmed',] %>%
  ggplot(aes(x=date, y=count)) +
  geom_area(aes(fill=Type), alpha=0.5) +
  labs(title=paste0('Numbers of Cases Worldwide - ', max.date.txt)) +
  scale_fill_manual(values=c('pink', 'green', 'orange')) +
  theme(legend.title=element_blank(), legend.position='bottom',
  plot.title = element_text(size=7),
  axis.title.x=element_blank(),
  axis.title.y=element_blank(),
  legend.key.size=unit(0.2, 'cm'),
  legend.text=element_text(size=6),
  axis.text=element_text(size=7),
  axis.text.x=element_text(angle=45, hjust=1))

plot2 <- world.long %>%
  ggplot(aes(x=date, y=count)) +
  geom_line(aes(color=Type)) +
  labs(title=paste0('Numbers of Cases Worldwide (log scale) - ', max.date.txt)) +
  scale_color_manual(values=c('purple', 'red', 'orange', 'black')) +
  theme(legend.title=element_blank(), legend.position='bottom',
  plot.title = element_text(size=7),
  axis.title.x=element_blank(),
  axis.title.y=element_blank(),
  legend.key.size=unit(0.2, 'cm'),
  legend.text=element_text(size=6),
  axis.text=element_text(size=7),
  axis.text.x=element_text(angle=45, hjust=1)) +
scale_y_continuous(trans='log10')
## show two plots side by side
grid.arrange(plot1, plot2, ncol=2)

```

```{r}
#sort by country and date
data_total %<>% arrange(country,date)

#daily increases of deaths and recovered cases
#set NA to the increases on day1
n <- nrow(data_total)
day1 <- min(data_total$date)
data_total %<>% mutate(new.confirmed = confirmed - c(NA,head(confirmed,-1)),
                 new.deaths = deaths - c(NA,head(deaths,-1)) ,
                 new.recovered = recovered - c(NA,head(recovered,-1)))

#change negative number of new case to zero
data_total %<>% mutate(new.confirmed = ifelse(new.confirmed < 0,0,new.confirmed),
                       new.deaths = ifelse(new.deaths < 0,0,new.deaths),
                       new.recovered = ifelse(new.recovered < 0,0,new.recovered))


#death rate based on total deaths and recovered cases
data_total %<>% mutate(rate.upper = (100*deaths/(deaths+recovered)) %>% round(1))
#lower bound: death rate based on total confirmed cases
data_total %<>% mutate(rate.lower = (100*deaths/confirmed) %>% round(1))
#death rate based on number of death/recovered on every single day
data_total %<>% mutate(rate.daily = (100*new.deaths/(new.deaths+new.recovered)) %>% round(1))

View(data_total)
#covert from wide to long format,for drawing area plots
#dataSelect1 <- sqldf("select Country,Date,confirmed,recovered,deaths from data_total")
#data_total

```

```{r}
data.world <- data_total[data_total$country == 'World',]
rownames(data.world) <- NULL
## current confirmed and daily new confirmed
plot1 <- ggplot(data.world, aes(x=date, y=current.confirmed)) +
  geom_point() + geom_smooth() +
  xlab('') + ylab('Count') + labs(title='Current Confirmed Cases') +
  theme(axis.text.x=element_text(angle=45, hjust=1))
plot2 <- ggplot(data.world, aes(x=date, y=new.confirmed)) +
  geom_point() + geom_smooth() +
  xlab('') + ylab('Count') + labs(title='Daily New Confirmed Cases') +
  theme(axis.text.x=element_text(angle=45, hjust=1))
## show two plots side by side
grid.arrange(plot1, plot2, ncol=2)

```

```{r}
## a scatter plot with a smoothed line and vertical x-axis labels
plot1 <- ggplot(data.world, aes(x=date, y=deaths)) +
  geom_point() + geom_smooth() +
  xlab('') + ylab('Count') + labs(title='Accumulative Deaths') +
  theme(axis.text.x=element_text(angle=45, hjust=1))
plot2 <- ggplot(data.world, aes(x=date, y=recovered)) +
  geom_point() + geom_smooth() +
  xlab('') + ylab('Count') + labs(title='Accumulative Recovered Cases') +
  theme(axis.text.x=element_text(angle=45, hjust=1))
plot3 <- ggplot(data.world, aes(x=date, y=new.deaths)) +
  geom_point() + geom_smooth() +
  xlab('') + ylab('Count') + labs(title='New Deaths') +
  theme(axis.text.x=element_text(angle=45, hjust=1))
plot4 <- ggplot(data.world, aes(x=date, y=new.recovered)) +
  geom_point() + geom_smooth() +
  xlab('') + ylab('Count') + labs(title='New Recovered Cases') +
  theme(axis.text.x=element_text(angle=45, hjust=1))
## show four plots together, with 2 plots in each row
grid.arrange(plot1, plot2, plot3, plot4, nrow=2)

```

```{r}
data.long <- data_total[,!(names(data_total) %in% c("new.confirmed","new.deaths","new.recovered","rate.upper","rate.lower","rate.daily"))]
#View(data.long)
data.long <- melt(data.long,id = c("country","date")) 
#View(data.long)
data.long <- data.long %>% rename(c("variable" = "Type")) %>% rename(c("value" = "count"))

data.long$Type <- as.character(data.long$Type)
data.long$Type[data.long$Type == "confirmed"] <- "Total Confirmed"
data.long$Type[data.long$Type == "current.confirmed"] <- "Current Confirmed"
data.long$Type[data.long$Type == "recovered"] <- "Recovered"
View(data.long)


rates.long <- data_total[,!(names(data_total) %in% c("new.confirmed","new.deaths","new.recovered","confirmed","current.confirmed","recovered","deaths"))]
#View(data.long)
rates.long <- melt(rates.long,id = c("country","date")) 
rates.long <- rates.long %>% rename(c("variable" = "Type")) %>% rename(c("value" = "count"))

rates.long$Type <- as.character(rates.long$Type)
rates.long$Type[rates.long$Type == "rate.daily"] <- "Daily"
rates.long$Type[rates.long$Type == "rate.lower"] <- "Lower Bound"
rates.long$Type[rates.long$Type == "rate.upper"] <- "Upper Bound"
View(rates.long)  
#set factor levels to show them in a desirable order

```


```{r}
#ranking by confirmed case
head(data_total)
dataDate <- data_total[data_total$date  == "2020-08-31",]%>%rename(c("rate.lower" = "death.rate"))
head(dataDate)
data.latest.all <- dataDate[,c("country","date","confirmed","new.confirmed","current.confirmed","recovered","deaths","new.deaths","death.rate")]
data.latest.all <- arrange(data.latest.all,desc(confirmed)) %>% mutate(ranking = rank(desc(confirmed)))

#View(data.latest.all)
k <- 20
#top 20 countries 21 incl.'World'
head(data.latest.all)
top.countries <- data.latest.all[data.latest.all$ranking <= k+1,] %>% arrange(ranking) 
top.countries
View(top.countries)

```

```{r}
#add 'Others'
data.latest <- data.latest.all[!is.na(data.latest.all$country),] %>% 
  mutate(country = ifelse(ranking <= k + 1, as.character(country), 'Others')) 
  mutate(data.latest, country = country %>% factor(levels=c(as.character(top.countries), 'Others')))
  
data.latest <-  ddply(data.latest, .(country, date), summarise,
                      confirmed = sum(confirmed), new.confirmed = sum(new.confirmed),
                      current.confirmed = sum(current.confirmed),
                      recovered = sum(recovered), deaths = sum(deaths), new.deaths = sum(new.deaths)) %>%
mutate(death.rate=(100 * deaths/confirmed) %>% round(1)) 

data.latest <- arrange(data.latest,desc(confirmed)) %>% mutate(ranking = rank(desc(confirmed)))
data.latest <- data.latest[,c("country", "confirmed", "deaths", "death.rate", "new.confirmed", "new.deaths", "current.confirmed")] 
data.latest <- data.latest[c(1:2, 4:nrow(data.latest), 3),]
rownames(data.latest) <- NULL

data.latest
View(data.latest)

```
```{r}
data.latest.long <- data.latest[data.latest$country != 'World',] 
data.latest.long <- melt(data.latest.long, id = c("country")) 
data.latest.long <- data.latest.long%>% rename(c("variable" = "Type")) %>% rename(c("value" = "count"))
data.latest.long$Type <- as.character(data.latest.long$Type)
data.latest.long$Type[data.latest.long$Type == "confirmed"] <- "Total Confirmed"
data.latest.long$Type[data.latest.long$Type == "deaths"] <- "Total deaths"
data.latest.long$Type[data.latest.long$Type == "death.rate"] <- "Death Rate (%)"
data.latest.long$Type[data.latest.long$Type == "new.confirmed"] <- "New Confirmed"
data.latest.long$Type[data.latest.long$Type == "new.deaths"] <- "New Deaths"
data.latest.long$Type[data.latest.long$Type == "current.confirmed"] <- "Current Confirmed"
View(data.latest.long)
```

```{r}
data.latest.long %>% ggplot(aes(x=country, y=count, fill=country, group=country)) +
  geom_bar(stat='identity') +
  geom_text(aes(label=count, y=count), size=2, vjust=0) +
  xlab('') + ylab('') +
  labs(title=paste0('Top 20 Countries with Most Confirmed Cases- ', max.date.txt)) +
  scale_fill_discrete(name='Country', labels=aes(count)) +
  theme(legend.title=element_blank(),
        legend.position='none',
        plot.title=element_text(size=11),
        axis.text=element_text(size=7),
        axis.text.x=element_text(angle=45, hjust=1)) +
  facet_wrap(~Type, ncol=1, scales='free_y')

```

```{r}
data <- odbcConnect("coronavirus19",uid = "root",pwd = "1234" )
#View(datapop)
#Data Cleaning
raw.temp <- sqlQuery(data, "SELECT * FROM World_Temp")
raw.temp <- raw.temp[!(names(raw.temp) %in% c("MyUnknownColumn"))] %>% rename(c("Country" = "country")) %>% rename(c("City" = "city")) %>% rename(c("Continent" = "continent"))
raw.temp$country[raw.temp$country == "United States"] <- "US"
#View(data.temp)

data.temp <- raw.temp[, names(raw.temp) %in% c("country", "city", "Apr", "May", "Jun", "Jul", "Aug")] 
data.temp <- data.frame(country = data.temp[,1], city = data.temp[,2], avg.temp = rowMeans(data.temp[,-c(1:2)])) 
data.temp <- aggregate(avg.temp ~ country, data = data.temp.all, mean) %>%
  mutate(avg.temp = (avg.temp %>% round(1)))
View(data.temp)
```

```{r}
datapop <- sqlQuery(data, "SELECT * FROM population")
datapop <- datapop %>% rename(c("Country" = "country")) %>% rename(c("Population (2020)" = "pop")) 
datapop
data_total.all <- dataDate %>% merge(datapop, by = "country") 
data_total.all <- mutate(data_total.all, 
                         confirmed.rate = ((100 * confirmed / pop) %>% round(1)),
                         recovered.rate = ((100 * recovered / confirmed )%>% round(1))
                         )
                         
data_total.all
```

```{r}
data_total.temp <- data_total.all %>% merge(data.temp, by = "country")
data_total.temp

data_total.temp.top <- data_total.all[, names(data_total.all) %in% c("country","new.recovered", "rate.upper", "pop", "confirmed.rate", "recovered.rate")] %>%
  merge(data.temp, by = "country") %>% merge(top.countries, by = "country") %>% arrange(ranking)
data_total.temp.top
```


```{r}
# graph: top 20 countries temperature 
g.temp.top <- data_total.temp.top[(names(data_total.temp.top) %in% c("country", "avg.temp"))] 
g.temp.top %>%
  ggplot(aes(country ,avg.temp, fill = factor(country))) + 
  geom_col() +
  theme(axis.text.x = element_text(angle = 90,  vjust = 1)) +
  labs(title = 'Average World Temperature in April - August')
g.temp.top

```
```{r}
# rates of top countries compared with temperature
temp.top.rate <- data_total.temp.top[,(names(data_total.temp.top) %in% c("country","avg.temp", "confirmed.rate", "death.rate", "recovered.rate"))]
temp.top.rate
temp.top.rate <- melt(temp.top.rate, id = c("country"))
temp.top.rate <- temp.top.rate %>% rename(c("variable" = "Type")) %>% rename(c("value" = "count"))
temp.top.rate$Type <- as.character(temp.top.rate$Type)
#top.temp.long$Type[top.temp.long$Type == "confirmed"] <- "Total Confirmed"
#View(temp.top.rate)

temp.top.rate %>% ggplot(aes(x=country, y=count, fill=country, group=country)) +
  geom_bar(stat='identity') +
  geom_text(aes(label=count, y=count), size=3, vjust=-0.5) +
  xlab('') + ylab('Rate') +
  labs(title = 'Average World Temperature compared to Rates') +
  scale_fill_discrete(name='Country', labels=aes(count)) +
  theme(legend.title=element_blank(),
        legend.position='none',
        plot.title=element_text(size=10),
        axis.text=element_text(size=7.5),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        axis.text.x = element_text(angle=45, hjust = 1)) +
  facet_wrap(~Type, ncol=1, scales='free_y')
```
```{r}
temp.top.rate <- temp.top.rate %>%
  ggplot(aes(x = country, y = count, group = Type, color = Type)) + 
  geom_line() + 
  xlab("") +
  ylab("") +
  theme(axis.text.x = element_text(angle = 90,  vjust = 1)) +
  labs(title = 'Average World Temperature compared to Rates')
temp.top.rate
```

```{r}
continent.temp <- data.temp[,(names(data.temp) %in% c("country","city","continent","Apr", "May", "Jun", "Jul", "Aug"))]
#View(continent.temp)

count.continent <- continent.temp[,!(names(continent.temp) %in% c("country"))]
count.continent <- aggregate(city ~ continent, data = count.continent, length)
count.continent

continent.long <- continent.temp[,!(names(continent.temp) %in% c("country", "city"))] %>%
  melt(id = c("continent"), variable.name = "month", value.name = "avg.temp") 
continent.long <- aggregate(avg.temp ~ continent + month, data = continent.long, sum)

data.latest.continent <- continent.long %>% merge(count.continent) %>%
  mutate(avg.temp = (avg.temp / city) %>% round(1))

data.latest.continent <- data.latest.continent[,!(names(data.latest.continent) %in% c("city"))]
data.latest.continent

data.latest.continent %>% 
  ggplot(aes(x = month, y = avg.temp, group = continent, color = continent)) +
  geom_line(size = 1) 
```

```{r}
#topcountries.nw <- top.countries[top.countries$country != "World",]
#View(topcountries.nw)
lat.long <- raw.confirmed[,(names(raw.confirmed) %in% c("Province.State", "Country.Region", "Lat", "Long"))] %>% rename(c("Province.State" = "city")) %>% rename(c("Country.Region" = "country"))
lat.long <- lat.long[lat.long$city == "",]
lat.long <- lat.long[,!(names(lat.long) %in% c("city"))]
lat.long

top.latlong <- lat.long %>% merge(data_total.temp.top, by = "country") %>%
#%>% merge(dataDate[,names(dataDate) %in% c("confirmed", "")], by = "country")
  mutate(ranking = rank(desc(confirmed))) %>% arrange(ranking)

top.latlong <- top.latlong[,(names(top.latlong) %in% c("country", "avg.temp", "Lat", "Long", "confirmed", "deaths", "recovered", "ranking"))]
label.top <- top.latlong 
label.top <- label.top %>% 
  mutate(txt=paste0('<b>',ranking, '</b>'))
label.top$txt <- label.top$txt %>% lapply(htmltools::HTML)
label.top
#View(top.latlong)

```

```{r}
m.top <- top.latlong
m.top$avg.temp <- as.numeric(m.top[, 4])
m.top <- m.top %>%
  mutate(txt=paste0('<b>',ranking, '</b>',
                    '<br/>','<b>',country, '</b>',
                    '<br/>', "Temperature:  ",avg.temp, ' °C',
                    '<br/>', "Confirmed:  ", confirmed, 
                    '<br/>', "Deaths: ", deaths,
                    '<br/>', "Recovered: ", recovered
                    )) 
m.top$txt <- m.top$txt %>% lapply(htmltools::HTML)
m.top

test.m <- mean(m.top[,c("avg.temp")])
test.m
```


```{r}
world.latlong <- lat.long %>% merge(data_total.temp, by = "country") 
world.latlong <- world.latlong[!(world.latlong$country %in% as.character(top.countries.name)),]
#world.latlong

m.world <- world.latlong 
m.world$avg.temp <- as.numeric(m.world[, names(m.world) %in% c("avg.temp")])
m.world <- m.world %>% 
  mutate(txt=paste0('<b>',country, '</b>',
                    '<br/>', "Temperature:  ",avg.temp, ' °C',
                    '<br/>', "Confirmed:  ", confirmed, 
                    '<br/>', "Deaths: ", deaths,
                    '<br/>', "Recovered: ", recovered
                    )) 
m.world$txt <- m.world$txt %>% lapply(htmltools::HTML)
m.world


wpal <- colorNumeric("YlOrRd", m.world$avg.temp, n = 4)
  
#View(m.world)
topIcon <- makeIcon("star.png",
  #iconUrl = "https://static.vecteezy.com/system/resources/previews/001/189/063/non_2x/star-rounded-png.png",
  iconWidth = 10, iconHeight = 10
  #iconAnchorX = 20, iconAnchorY = 20
  
)
  
m <- leaflet(width=1200, height=800) %>% addTiles()  
m %<>%  addCircleMarkers(m.world$Long, m.world$Lat,
                        # radius=2+log2(x$confirmed),
                        radius=10,#*log2(m.world$avg.temp),
                        stroke=F,
                        #color='red',
                        color = wpal(m.world$avg.temp), 
                        fillOpacity=0.5,
                        #popup=label.top$txt
                        label= m.world$txt,
                        group = "World"
                        ) %>%
  
  addCircleMarkers(m.top$Long, m.top$Lat,
                        # radius=2+log2(x$confirmed),
                        radius=10,#*log2(m.world$avg.temp),
                        stroke=F,
                        #color='red',
                        color = wpal(m.top$avg.temp), 
                        fillOpacity=0.5,
                        #popup=label.top$txt
                        label= m.top$txt,
                        group = "Top 20 Countries"
                        ) %>%
  
  addLabelOnlyMarkers(label.top$Long, label.top$Lat, label = label.top$txt,
                      labelOptions = labelOptions(noHide = TRUE, textOnly = TRUE, 
                                                  direction = "head", 
                                                  offset = c(5,5)),
                      group = "Top 20 Countries") %>%
  
  addLegend("bottomright", pal = wpal, values = m.world$avg.temp, opacity = 1,
            labFormat = labelFormat(suffix = " °C"),
            title = "Temperature") %>% 
  
  addLayersControl(
    #baseGroups = c("OSM (default)", "Toner", "Toner Lite"),
    overlayGroups = c("World", "Top 20 Countries"),
    options = layersControlOptions(collapsed = FALSE)
  )
m

```
```{r}
first.date <- as.Date("2020-04-01")
#last.date <- seq(as.Date("2020-05-01"),length=5,by="months")-1

data_total.month <- data_total[, c(1:5)] %>%
  mutate(month.confirmed = confirmed - c(NA,head(confirmed,-1)),
         month.deaths = deaths - c(NA,head(deaths,-1)) ,
         month.recovered = recovered - c(NA,head(recovered,-1)))

data_total.month$month.confirmed[data_total.month$date %in% first.date] <- 0
data_total.month$month.deaths[data_total.month$date %in% first.date] <- 0
data_total.month$month.recovered[data_total.month$date %in% first.date] <- 0

#View(data_total.month)

data_total.mean <- aggregate(cbind(month.confirmed, month.deaths,month.recovered) ~ month(date) + country,
             data=data_total.month ,FUN=mean)

data_total.mean <- data_total.mean %>% 
  mutate(month.confirmed = month.confirmed %>% round(1),
         month.deaths = month.deaths %>% round(1) ,
         month.recovered = month.recovered %>% round(1)
         ) %>%
  rename(c("month(date)" = "month"))

data_total.mean$month[data_total.mean$month == 4] <- "Apr"
data_total.mean$month[data_total.mean$month == 5] <- "May"
data_total.mean$month[data_total.mean$month == 6] <- "Jun"
data_total.mean$month[data_total.mean$month == 7] <- "Jul"
data_total.mean$month[data_total.mean$month == 8] <- "Aug"

View(data_total.mean)
```

```{r}
data.temp.month <- raw.temp[, names(raw.temp) %in% c("country", "city", "Apr", "May", "Jun", "Jul", "Aug")] 
data.temp.month <- aggregate(. ~ country, data = data.temp.month[,-c(2)], mean) 
data.temp.month[-c(1)] <- data.temp.month[-c(1)] %>% round(1)
data.temp.month <- melt(data.temp.month, id = c("country")) %>% rename(c("variable" = "month")) %>% rename(c("value" = "avg.temp"))
data.temp.month
```

```{r}
top.countries
```

```{r}
top.countries.name <- top.countries[,1]
data.latest.temp <- data_total.mean %>% merge(data.temp.month[data.temp.month$country %in% top.countries.name,]) 
data.latest.temp
```

```{r}
#data_total.month
data_total.avg <- aggregate(cbind(month.confirmed, month.deaths,month.recovered) ~ country,
             data=data_total.month ,FUN=mean)

data_total.avg <- data_total.avg %>% 
  mutate(avg.confirmed = month.confirmed %>% round(1),
         avg.deaths = month.deaths %>% round(1) ,
         avg.recovered = month.recovered %>% round(1)
         ) 

data_total.avg <- data_total.avg[, c(1, 5:7)]
#data_total.avg
```
```{r}
data_total.avg.top <- data_total.avg[data_total.avg$country %in% as.character(top.countries.name),] 
data_total.avg.top.temp <- data_total.avg.top %>% merge(data.temp)
data_total.avg.top.temp
```
```{r}
data.latest
world.confirmed <- data.latest[1,2]

world.ratio <- data.latest[!(data.latest$country == c("World")),1:2] %>%
  mutate(percentage =  (100 *confirmed / world.confirmed) %>% round(1))

rownames(world.ratio) <- NULL
View(world.ratio)

write.csv(world.ratio,"D:/4D/Pre Project/files/world_ratio.csv", row.names = FALSE)
```
















